# Runs all galleries against staging
name: Test Staging
on:
  pull_request_target:
    branches:
      - main

jobs:
  test-staging:
    runs-on: ubuntu-latest
    # TODO: If GitHub gives access to the commit message in PRs, this gets easier.
    # if: "contains(github.event.head_commit.message, 'test-staging')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

        # with:
        #   token: ${{ secrets.PANGEOBOT_TOKEN }}

      - name: get commit message
        run: |
           echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV

      - name: step1
        if: contains( env.COMMIT_MESSAGE , 'test-staging' )
        run: echo hello

      - name: step2
        if: "!contains( env.COMMIT_MESSAGE , 'test-staging' )"
        run: echo $COMMIT_MESSAGE

      - name: context
        run: echo ${{ github }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
